# Generated by Django 5.0.6 on 2024-05-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTime', '0002_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
