# Generated by Django 5.0.6 on 2024-05-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTime', '0003_staff_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='surname',
        ),
    ]
