# Generated by Django 5.0.6 on 2024-05-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTime', '0004_remove_staff_email_remove_staff_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='ShiftEndTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='ShiftStartTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='ShiftType',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=8),
        ),
        migrations.AddField(
            model_name='staff',
            name='TotalWorkHours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='surname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
