# Generated by Django 5.0.6 on 2024-05-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkTime', '0006_alter_staff_shiftendtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='ShiftType',
        ),
    ]
